/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto1;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
/**
 *
 * @author valen
 */
public class Interfaz extends javax.swing.JPanel {
    private GrafoBio miGrafo;   

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        miGrafo = new GrafoBio();
        actualizarEstadoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        GestionArchivos = new javax.swing.JPanel();
        CargarRed = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ModificarRed = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PesoModificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AddInteraccion = new javax.swing.JButton();
        EliminarProteina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NuevaNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NuevaConex = new javax.swing.JTextField();
        AddProteina = new javax.swing.JToggleButton();
        EliminarModificacion = new javax.swing.JComboBox<>();
        PAModificacion = new javax.swing.JComboBox<>();
        PBModificacion = new javax.swing.JComboBox<>();
        AnalisisRed = new javax.swing.JPanel();
        BFS = new javax.swing.JButton();
        Hubs = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        PADijkstra = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        PBDijkstra = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        CalcularDijkstra = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        ScrollMostrarAnalisis = new javax.swing.JScrollPane();
        MostrarAnalisis = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Vizualizar = new javax.swing.JPanel();
        MostrarRed = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setToolTipText("");

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));

        GestionArchivos.setBackground(new java.awt.Color(255, 255, 255));
        GestionArchivos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión de Archivos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI Emoji", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        GestionArchivos.setForeground(new java.awt.Color(0, 0, 0));

        CargarRed.setBackground(new java.awt.Color(103, 200, 185));
        CargarRed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CargarRed.setForeground(new java.awt.Color(255, 255, 255));
        CargarRed.setText("Cargar Red ");
        CargarRed.setToolTipText("Carga el archivo CVS o TXT de la red.");
        CargarRed.addActionListener(this::CargarRedActionPerformed);

        lblArchivo.setBackground(new java.awt.Color(255, 255, 255));
        lblArchivo.setForeground(new java.awt.Color(0, 0, 0));
        lblArchivo.setText("Archivo actual : Ninguno");

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Carga un archivo CSV o TXT con la información de la red de proteínas");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N

        javax.swing.GroupLayout GestionArchivosLayout = new javax.swing.GroupLayout(GestionArchivos);
        GestionArchivos.setLayout(GestionArchivosLayout);
        GestionArchivosLayout.setHorizontalGroup(
            GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionArchivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionArchivosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(GestionArchivosLayout.createSequentialGroup()
                        .addGroup(GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CargarRed, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GestionArchivosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblArchivo)))
                        .addGap(18, 18, 18)
                        .addGroup(GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GestionArchivosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GestionArchivosLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(0, 6, Short.MAX_VALUE))))))
        );
        GestionArchivosLayout.setVerticalGroup(
            GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionArchivosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(GestionArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionArchivosLayout.createSequentialGroup()
                        .addComponent(CargarRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArchivo)
                        .addContainerGap())
                    .addGroup(GestionArchivosLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))))
        );

        jTabbedPane1.addTab("Archivos", GestionArchivos);

        ModificarRed.setBackground(new java.awt.Color(255, 255, 255));
        ModificarRed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificación de la Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI Emoji", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        ModificarRed.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Proteina Origen");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Proteina Destino");

        PesoModificacion.setBackground(new java.awt.Color(170, 192, 189));
        PesoModificacion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Resistencia");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seleccionar ");

        AddInteraccion.setBackground(new java.awt.Color(103, 200, 185));
        AddInteraccion.setForeground(new java.awt.Color(0, 0, 0));
        AddInteraccion.setText("Agregar Interaccion");
        AddInteraccion.addActionListener(this::AddInteraccionActionPerformed);

        EliminarProteina.setBackground(new java.awt.Color(103, 200, 185));
        EliminarProteina.setForeground(new java.awt.Color(0, 0, 0));
        EliminarProteina.setText("Aplicar farmaco");
        EliminarProteina.addActionListener(this::EliminarProteinaActionPerformed);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Elimina una proteína");
        jLabel2.setToolTipText("Simula el efecto de un fármaco apagando una proteína");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Agrega una nueva interacción");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Agrega una nueva proteína");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Nombre de la Proteína");

        NuevaNombre.setBackground(new java.awt.Color(170, 192, 189));
        NuevaNombre.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        NuevaNombre.setForeground(new java.awt.Color(51, 51, 51));
        NuevaNombre.setText("Ej. P54");
        NuevaNombre.addActionListener(this::NuevaNombreActionPerformed);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Proteinas conexas y resistencias");

        NuevaConex.setBackground(new java.awt.Color(170, 192, 189));
        NuevaConex.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        NuevaConex.setForeground(new java.awt.Color(51, 51, 51));
        NuevaConex.setText("Ej. P51:5, M8:12, ...");
        NuevaConex.setToolTipText("Debe escribir las conexiones que la nueva proteina tenga con las existentes en la red de la forma \"Proteina:Resistencia\"");
        NuevaConex.addActionListener(this::NuevaConexActionPerformed);

        AddProteina.setBackground(new java.awt.Color(103, 200, 185));
        AddProteina.setForeground(new java.awt.Color(0, 0, 0));
        AddProteina.setText("Agregar Proteina");
        AddProteina.addActionListener(this::AddProteinaActionPerformed);

        EliminarModificacion.setBackground(new java.awt.Color(221, 253, 255));
        EliminarModificacion.setForeground(new java.awt.Color(0, 0, 0));
        EliminarModificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PAModificacion.setBackground(new java.awt.Color(221, 253, 255));
        PAModificacion.setForeground(new java.awt.Color(0, 0, 0));
        PAModificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PBModificacion.setBackground(new java.awt.Color(221, 253, 255));
        PBModificacion.setForeground(new java.awt.Color(0, 0, 0));
        PBModificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout ModificarRedLayout = new javax.swing.GroupLayout(ModificarRed);
        ModificarRed.setLayout(ModificarRedLayout);
        ModificarRedLayout.setHorizontalGroup(
            ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarRedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(ModificarRedLayout.createSequentialGroup()
                        .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarRedLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(PAModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ModificarRedLayout.createSequentialGroup()
                                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PesoModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PBModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(AddInteraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarRedLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(NuevaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(NuevaConex, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarRedLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddProteina)
                                .addGap(14, 14, 14))))
                    .addGroup(ModificarRedLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EliminarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(EliminarProteina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        ModificarRedLayout.setVerticalGroup(
            ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarRedLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PAModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(PBModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NuevaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(PesoModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevaConex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddInteraccion)
                    .addComponent(AddProteina))
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(EliminarProteina)
                    .addComponent(EliminarModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Red", ModificarRed);

        AnalisisRed.setBackground(new java.awt.Color(255, 255, 255));
        AnalisisRed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Análisis de la Red", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI Emoji", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        AnalisisRed.setForeground(new java.awt.Color(0, 0, 0));

        BFS.setBackground(new java.awt.Color(103, 200, 185));
        BFS.setForeground(new java.awt.Color(0, 0, 0));
        BFS.setText("Detectar");
        BFS.addActionListener(this::BFSActionPerformed);

        Hubs.setBackground(new java.awt.Color(103, 200, 185));
        Hubs.setForeground(new java.awt.Color(0, 0, 0));
        Hubs.setText("Identificar Hubs");
        Hubs.setToolTipText("Haz clic para identificar las proteínas con más conexiones en la red");
        Hubs.addActionListener(this::HubsActionPerformed);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ruta Mas Corta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI Emoji", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));

        PADijkstra.setBackground(new java.awt.Color(221, 253, 255));
        PADijkstra.setForeground(new java.awt.Color(51, 51, 51));
        PADijkstra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Proteina Origen");

        PBDijkstra.setBackground(new java.awt.Color(221, 253, 255));
        PBDijkstra.setForeground(new java.awt.Color(51, 51, 51));
        PBDijkstra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Proteina Destino");

        CalcularDijkstra.setBackground(new java.awt.Color(103, 200, 185));
        CalcularDijkstra.setForeground(new java.awt.Color(0, 0, 0));
        CalcularDijkstra.setText("Calcular");
        CalcularDijkstra.addActionListener(this::CalcularDijkstraActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(PADijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(PBDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(CalcularDijkstra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PADijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PBDijkstra))
                .addGap(18, 18, 18)
                .addComponent(CalcularDijkstra)
                .addGap(26, 26, 26))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("<html>Detección de complejos<br>proteicos</html>");

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("<html>Búsqueda de proteínas<br>más escenciales</html>");

        jProgressBar1.setToolTipText("Muestra el progreso de carga del archivo o del análisis de la red");

        MostrarAnalisis.setEditable(false);
        MostrarAnalisis.setBackground(new java.awt.Color(204, 204, 204));
        MostrarAnalisis.setColumns(20);
        MostrarAnalisis.setForeground(new java.awt.Color(0, 0, 0));
        MostrarAnalisis.setRows(5);
        MostrarAnalisis.setCaretColor(new java.awt.Color(153, 255, 255));
        MostrarAnalisis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScrollMostrarAnalisis.setViewportView(MostrarAnalisis);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Progreso...");

        javax.swing.GroupLayout AnalisisRedLayout = new javax.swing.GroupLayout(AnalisisRed);
        AnalisisRed.setLayout(AnalisisRedLayout);
        AnalisisRedLayout.setHorizontalGroup(
            AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalisisRedLayout.createSequentialGroup()
                .addGroup(AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnalisisRedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(AnalisisRedLayout.createSequentialGroup()
                                .addGroup(AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BFS, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hubs, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(AnalisisRedLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ScrollMostrarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        AnalisisRedLayout.setVerticalGroup(
            AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnalisisRedLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AnalisisRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AnalisisRedLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BFS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hubs))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollMostrarAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Analizar Red", AnalisisRed);

        Vizualizar.setBackground(new java.awt.Color(255, 255, 255));

        MostrarRed.setBackground(new java.awt.Color(103, 200, 185));
        MostrarRed.setForeground(new java.awt.Color(0, 0, 0));
        MostrarRed.setText("Ver Red");
        MostrarRed.addActionListener(this::MostrarRedActionPerformed);

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Haz clic para vizualizar el grafo de la red de proteínas");
        jLabel16.setToolTipText("");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N

        javax.swing.GroupLayout VizualizarLayout = new javax.swing.GroupLayout(Vizualizar);
        Vizualizar.setLayout(VizualizarLayout);
        VizualizarLayout.setHorizontalGroup(
            VizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VizualizarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(VizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VizualizarLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(VizualizarLayout.createSequentialGroup()
                        .addComponent(MostrarRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VizualizarLayout.setVerticalGroup(
            VizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VizualizarLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VizualizarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(MostrarRed)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vizualizar", Vizualizar);

        Guardar.setBackground(new java.awt.Color(103, 200, 185));
        Guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.setToolTipText("Haz clic aquí para exportar los datos de la red actualizada a tu computadora.");
        Guardar.addActionListener(this::GuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Guardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

 /**
 *Botón: "Detectar" (BFS).
  
     *Ejecuta BFS sobre el grafo para encontrar componentes conexos (complejos proteicos).
     * Un “complejo” aquí significa: conjunto de proteínas que están conectadas entre sí por alguna ruta.
     * Imprime cada complejo con: número de complejo, tamaño y lista de IDs.
 * @param evt 
 */   
    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        MostrarAnalisis.append("\n");
        MostrarAnalisis.append("Iniciando escaneo de complejos (BFS)...\n");

        try {
            AnalisisGrafo analizador = new AnalisisGrafo(miGrafo);
            Lista<Lista<Proteina>> BFS = analizador.encontrarConexas(); 
            int totalComplejos = BFS.getSize();
            int numComplejo = 1; 
            Nodo<Lista<Proteina>> nodoComplejo = BFS.getInicio();
    
            while (nodoComplejo != null) {
                Lista<Proteina> complejoActual = nodoComplejo.getDato();
       
                StringBuilder nombresProteinas = new StringBuilder(); /**Arma string con todas las prpteinas de la isla complejo*/
                Nodo<Proteina> proteina = complejoActual.getInicio();
        
                while (proteina != null) {
                    nombresProteinas.append(proteina.getDato().getID());
                    if (proteina.getNext() != null) {
                        nombresProteinas.append(", "); 
                    }
            proteina = proteina.getNext();
                }
        MostrarAnalisis.append("Complejo " + numComplejo + " (" + complejoActual.getSize() + " proteínas): [" + nombresProteinas.toString() + "]\n");
        nodoComplejo = nodoComplejo.getNext();
        numComplejo++;
        }
    
        MostrarAnalisis.append("Se detectaron " + totalComplejos + " complejos proteicos.\n");
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al ejecutar BFS: " + e.getMessage(), "Error de Análisis", JOptionPane.ERROR_MESSAGE);
        }

        MostrarAnalisis.append("\n");
                
    }//GEN-LAST:event_BFSActionPerformed
 /**
     * Botón: "Ver Red" (Visualizar).
     *
     *Crea un grafo visual usando GraphStream.
     * Agrega nodos para cada proteína con su ID.
     * 
     *Agrega aristas evitando duplicados usando la regla
     * Muestra la ventana con {@code graphVisual.display()}.
     * 
     */
    private void MostrarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarRedActionPerformed
        System.setProperty("org.graphstream.ui", "swing");
        try{
            MostrarAnalisis.append("Generando visualización 2D de la red...\n");
            org.graphstream.graph.Graph graphVisual = new org.graphstream.graph.implementations.SingleGraph("Interactoma");
            graphVisual.setAttribute("ui.stylesheet", "node { fill-color: #3498db; size: 20px; text-size: 14px; text-color: black; } edge { fill-color: #7f8c8d; }");
            graphVisual.setAttribute("ui.antialias");
            Nodo<Proteina> auxProt = miGrafo.getListaProteinas().getInicio();
            while (auxProt != null) {
                Proteina p = auxProt.getDato();
                org.graphstream.graph.Node n = graphVisual.addNode(p.getID());
                n.setAttribute("ui.label", p.getID()); 
                auxProt = auxProt.getNext();
            }
            auxProt = miGrafo.getListaProteinas().getInicio();
            while (auxProt != null) {
                Proteina p = auxProt.getDato();
                String idA = p.getID();
                Nodo<Interaccion> auxInt = p.getAdyacentes().getInicio();
                while (auxInt != null) {
                    Interaccion inter = auxInt.getDato();
                    String idB = inter.getPB().getID();

                    if (idA.compareTo(idB) < 0) {
                        String idArista = idA + "-" + idB; 
                        graphVisual.addEdge(idArista, idA, idB);
                    }
                    auxInt = auxInt.getNext();
                    }
                    auxProt = auxProt.getNext();
                }
            graphVisual.display();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de visualización: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_MostrarRedActionPerformed
/**
 * Boton Guardar. Abre un {@link JFileChooser} en modo guardar.
     * Escribe el contenido del grafo actual a un archivo CSV.
     *
     * Guarda la red tal como está en memoria, incluyendo cambios hechos por botones.
 * @param evt 
 */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        JFileChooser file = new JFileChooser();
        if (file.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File archivoDestino = file.getSelectedFile();
            try {
                GestorArchivos gestor = new GestorArchivos();
                gestor.guardarRed(archivoDestino, miGrafo);

                MostrarAnalisis.append("Red guardada en " + archivoDestino.getName() + "\n");
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");

            } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}    }//GEN-LAST:event_GuardarActionPerformed
/**
     * Botón: "Agregar Interacción".
     
     * Lee 3 campos de texto: proteína origen, proteína destino y resistencia.
     * Intenta crear la arista en el grafo con {@code miGrafo.addInteraccion(origen, destino, peso)}.Si se logra, limpia inputs y refresca ComboBox.</li>
     * 
     */
    private void AddInteraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInteraccionActionPerformed

        String origen = (String) PAModificacion.getSelectedItem();
        String destino = (String)PBModificacion.getSelectedItem();
        String pesoStr = PesoModificacion.getText().trim();

        if (origen.isEmpty() || destino.isEmpty() || pesoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Error: Ningún campo puede estar vacío. Por favor, ingrese Origen, Destino y Resistencia.", 
                "Campos Incompletos", 
                JOptionPane.ERROR_MESSAGE);
            return; 
        }
      
        try {
            double peso = Double.parseDouble(pesoStr);
            boolean ok = miGrafo.addInteraccion(origen, destino, peso);
            if (!ok) {
                JOptionPane.showMessageDialog(this,
                    "No se pudo agregar la interacción. Verifique:\n- que ambas proteínas existan\n- que no sea duplicada\n- que la resistencia sea válida",
                    "Operación no realizada",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, 
                "Interacción entre " + origen + " y " + destino + " agregada con éxito.", 
                "Operación Exitosa", 
                JOptionPane.INFORMATION_MESSAGE);

            PesoModificacion.setText("");
            actualizarComboBoxes();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Error: El valor de la resistencia debe ser un número válido (Ej: 0.5, 10).", 
                "Dato Inválido", 
                JOptionPane.ERROR_MESSAGE);
}    }//GEN-LAST:event_AddInteraccionActionPerformed
/** Botón: "Cargar Red".
   * Abre un {@link JFileChooser} para que el usuario seleccione un archivo.
     * Reinicia el grafo actual, {@link GestorArchivos#cargarRed(File, GrafoBio)} 
     * para leer el archivo y poblar el grafo.
     * Actualiza los ComboBox 
     * Habilita los botones de análisis si ya hay proteínas.
     * Muestra un mensaje de advertencia (si no guardaste antes, pierdes cambios).
     * Actualiza el label {@code lblArchivo} con el nombre del archivo cargado.
     */
    private void CargarRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarRedActionPerformed
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto y CSV", "csv", "txt");
        file.setFileFilter(filtro);
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File archivoSeleccionado = file.getSelectedFile();
            try {
            GestorArchivos gestor = new GestorArchivos();
            miGrafo = new GrafoBio();
            gestor.cargarRed(archivoSeleccionado, miGrafo);
            actualizarComboBoxes();
            actualizarEstadoBotones();
            JOptionPane.showMessageDialog(this, 
                "Recuerde que al cargar un nuevo archivo, se perderán los datos actuales no guardados en memoria.\n¡Asegúrese de guardar primero si hizo cambios!", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            lblArchivo.setText("Archivo actual: " + archivoSeleccionado.getName());
            }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            System.out.println("Carga de archivo cancelada.");
        }
    }//GEN-LAST:event_CargarRedActionPerformed
/**
     * Botón: "Aplicar fármaco" (Eliminar proteína).
     *
     * Obtiene el elemento seleccionado del ComboBox {@code EliminarModificacion}.
     * Pide confirmación al usuario (YES/NO) porque esta operación es destructiva.</li>
     * Llama a {@code miGrafo.eliminarProteina(diana)}.
     *  
     */
    private void EliminarProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProteinaActionPerformed

        Object sel = EliminarModificacion.getSelectedItem();
        if (sel == null) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una proteína para aplicar el fármaco.",
                "Sin selección",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        String diana = sel.toString().trim();
        if (diana.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una proteína válida.",
                "Selección inválida",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opt = JOptionPane.showConfirmDialog(this,
            "¿Aplicar fármaco y eliminar '" + diana + "' junto con TODAS sus interacciones?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (opt != JOptionPane.YES_OPTION) return;

        boolean ok = miGrafo.eliminarProteina(diana);
        if (!ok) {
            JOptionPane.showMessageDialog(this,
                "No se pudo eliminar. La proteína '" + diana + "' no existe en la red.",
                "Operación no realizada",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        MostrarAnalisis.append("FÁRMACO APLICADO: Se eliminó '" + diana + "' y todas sus interacciones.\n");

        actualizarComboBoxes(); 
        actualizarEstadoBotones();

    }//GEN-LAST:event_EliminarProteinaActionPerformed
/**    * Botón: "Calcular" (Dijkstra).
     *  Lee proteína origen y destino desde ComboBox.
     *   Ejecuta {@link AnalisisGrafo#rutaMasCorta(String, String)} usando Dijkstra.
     *   Si hay ruta, imprime:La secuencia de proteínas: A -> ... -> B
     *   La resistencia total acumulada (distancia) almacenada en el nodo final.
     */
    private void CalcularDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularDijkstraActionPerformed
        if (PADijkstra.getSelectedItem() == null || PBDijkstra.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Seleccione proteína de origen y destino.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String origen = PADijkstra.getSelectedItem().toString();
        String destino = PBDijkstra.getSelectedItem().toString();
        if (origen.equals(destino)) {
            JOptionPane.showMessageDialog(this,
                "Seleccione proteínas distintas para calcular una ruta.",
                "Selección inválida",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        MostrarAnalisis.append("\n");
        MostrarAnalisis.append("Calculando ruta metabólica de " + origen + " a " + destino + "...\n");

        try {
            AnalisisGrafo analizador = new AnalisisGrafo(miGrafo);
            Lista<Proteina> ruta = analizador.rutaMasCorta(origen, destino);

            if (ruta == null) {
                MostrarAnalisis.append("No existe conexión entre " + origen + " y " + destino + ".\n");
            } else {
                StringBuilder rutaStr = new StringBuilder();
                Nodo<Proteina> actual = ruta.getInicio();
                double pesoTotal = 0.0;
                while (actual != null) {
                    Proteina p = actual.getDato();
                    rutaStr.append(p.getID());

                    if (actual.getNext() != null) {
                        rutaStr.append(" -> ");
                    } else {
                        pesoTotal = p.getDist(); 
                    }
                    actual = actual.getNext();
                }

                MostrarAnalisis.append("RUTA: " + rutaStr.toString() + "\n");
                MostrarAnalisis.append("RESISTENCIA TOTAL: " + pesoTotal + "\n");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en Dijkstra: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        MostrarAnalisis.append(" \n");
    }//GEN-LAST:event_CalcularDijkstraActionPerformed
/**
     * Botón: "Identificar Hubs".
     * Ejecuta {@link AnalisisGrafo#encontrarHubsAutomatico()}.
     *Ese método calcula un umbral dinámico basado en el promedio de grado del grafo.
     * Lista las proteínas cuyo grado (cantidad de conexiones) supera el umbral.
     */
    private void HubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HubsActionPerformed

        MostrarAnalisis.append("Escaneando la red en busca de Hubs...\n");

        try {
            AnalisisGrafo analizador = new AnalisisGrafo(miGrafo);
            Lista<Proteina> hubs = analizador.encontrarHubsAutomatico();
            int totalHubs = hubs.getSize();
            MostrarAnalisis.append("RESULTADO: Se detectaron " + totalHubs + " Hubs.\n");
            Nodo<Proteina> aux = hubs.getInicio();
            while (aux != null) {
                Proteina p = aux.getDato();
                MostrarAnalisis.append("- " + p.getID() + " (Conexiones: " + p.getGrado() + ")\n");
                aux = aux.getNext();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al buscar Hubs: " + e.getMessage());
        }
        MostrarAnalisis.append("\n");
            }//GEN-LAST:event_HubsActionPerformed

    private void NuevaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaNombreActionPerformed
         /**Pide ingresar el nombre de la nueva proteina*/  
    }//GEN-LAST:event_NuevaNombreActionPerformed

    private void NuevaConexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaConexActionPerformed

        /**Pide ingresar los nombres de las proteinas conexas y el peso de sus aristas, 
         * despues lo separa para crear bien las interacciones validando todo previamente*/ 
    }//GEN-LAST:event_NuevaConexActionPerformed
/**
     * Botón: "Aplicar fármaco" (Eliminar proteína).
     *
     *Obtiene el elemento seleccionado del ComboBox {@code EliminarModificacion}.
     * Valida, Pide confirmación al usuario (YES/NO) porque esta operación es destructiva.Llama a {@code miGrafo.eliminarProteina(diana)}.</li>
     * Si se eliminó, escribe en el panel de resultados y refresca ComboBox/botones.</li>
     * 
     */
    private void AddProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProteinaActionPerformed
        
        String nuevaProt = NuevaNombre.getText().trim().toUpperCase();
        String conexionesStr = NuevaConex.getText().trim().toUpperCase();

        if (nuevaProt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Debe ingresar el ID de la nueva proteína (ej: P54).",
                "Campo vacío",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            if (miGrafo.buscarProteina(nuevaProt) != null) {
                JOptionPane.showMessageDialog(this,
                    "La proteína '" + nuevaProt + "' ya existe en la red.",
                    "Duplicado",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            boolean okProt = miGrafo.addProteina(nuevaProt);
            if (!okProt) {
                JOptionPane.showMessageDialog(this,
                    "No se pudo agregar la proteína '" + nuevaProt + "'.",
                    "Operación no realizada",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            MostrarAnalisis.append("Se agregó la proteína: " + nuevaProt + "\n");
            if (!conexionesStr.isEmpty()) {
                String[] conectadas = conexionesStr.split(",");
                for (String conexion : conectadas) {
                    conexion = conexion.trim();

                    String[] partes = conexion.split(":");
                    if (partes.length != 2) {
                        MostrarAnalisis.append(" -> Formato inválido en '" + conexion
                            + "'. Use: Proteina:Resistencia (ej: P51:0.5)\n");
                        continue;
                    }
                    String protDestino = partes[0].trim();
                    String resistenciaStr = partes[1].trim();

                    double resistencia;
                    try {
                        resistencia = Double.parseDouble(resistenciaStr);
                    } catch (NumberFormatException e) {
                        MostrarAnalisis.append(" -> Resistencia inválida para '" + protDestino
                            + "': '" + resistenciaStr + "'\n");
                        continue;
                    }

                    if (miGrafo.buscarProteina(protDestino) == null) {
                        MostrarAnalisis.append(" -> No se creó conexión: '" + protDestino
                            + "' no existe en la red.\n");
                        continue;
                    }

                    boolean okInter = miGrafo.addInteraccion(nuevaProt, protDestino, resistencia);
                    if (okInter) {
                        MostrarAnalisis.append(" -> Conectada con " + protDestino
                            + " (Resistencia: " + resistencia + ")\n");
                    } else {
                        MostrarAnalisis.append(" -> No se pudo conectar con " + protDestino
                            + " (posible duplicado o datos inválidos).\n");
                    }
                }
            }

            actualizarComboBoxes();
            actualizarEstadoBotones();
            NuevaNombre.setText("Ej. P54");
            NuevaConex.setText("Ej. P51:5, M8:12, ...");

            JOptionPane.showMessageDialog(this,
                "Proteína agregada. Revise el panel de resultados para ver conexiones/errores.",
                "Operación completada",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al agregar: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_AddProteinaActionPerformed

    /**
     * Recorre el grafo actual y llena los menús desplegables de la interfaz
     * con los nombres de las proteínas disponibles.
     */
    private void actualizarComboBoxes() {
        PADijkstra.removeAllItems();
        PBDijkstra.removeAllItems();
        EliminarModificacion.removeAllItems();

        if (miGrafo == null || miGrafo.getListaProteinas().getSize() == 0) {
            return; 
        }
        Nodo<Proteina> aux = miGrafo.getListaProteinas().getInicio();
        while (aux != null) {
            Proteina p = aux.getDato();
            String idProteina = p.getID();
            PADijkstra.addItem(idProteina);
            PBDijkstra.addItem(idProteina);
            EliminarModificacion.addItem(idProteina);
            aux = aux.getNext();
        }
    }
    /**
 * Habilita o deshabilita los botones de análisis
 * dependiendo de si el grafo contiene proteínas.
 */
    private void actualizarEstadoBotones() {

        boolean hayDatos = (miGrafo != null 
            && miGrafo.getListaProteinas().getSize() > 0);

        BFS.setEnabled(hayDatos);
        CalcularDijkstra.setEnabled(hayDatos);
        Hubs.setEnabled(hayDatos);
        MostrarRed.setEnabled(hayDatos);
        Guardar.setEnabled(hayDatos);
        if (!hayDatos) {
            MostrarAnalisis.setText("");
            MostrarAnalisis.append("\n");
            MostrarAnalisis.append("La red está vacía.\n");
            MostrarAnalisis.append("Cargue un archivo CSV o agregue proteínas manualmente.\n");
        } else if (MostrarAnalisis.getText().contains("La red está vacía")) {
          MostrarAnalisis.setText("");
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInteraccion;
    private javax.swing.JToggleButton AddProteina;
    private javax.swing.JPanel AnalisisRed;
    private javax.swing.JButton BFS;
    private javax.swing.JButton CalcularDijkstra;
    private javax.swing.JButton CargarRed;
    private javax.swing.JComboBox<String> EliminarModificacion;
    private javax.swing.JButton EliminarProteina;
    private javax.swing.JPanel GestionArchivos;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Hubs;
    private javax.swing.JPanel ModificarRed;
    private javax.swing.JTextArea MostrarAnalisis;
    private javax.swing.JButton MostrarRed;
    private javax.swing.JTextField NuevaConex;
    private javax.swing.JTextField NuevaNombre;
    private javax.swing.JComboBox<String> PADijkstra;
    private javax.swing.JComboBox<String> PAModificacion;
    private javax.swing.JComboBox<String> PBDijkstra;
    private javax.swing.JComboBox<String> PBModificacion;
    private javax.swing.JTextField PesoModificacion;
    private javax.swing.JScrollPane ScrollMostrarAnalisis;
    private javax.swing.JPanel Vizualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblArchivo;
    // End of variables declaration//GEN-END:variables
}
